const uint16_t audio[][AUDIO] = {
	[GAME_PMCG2] = {
		[MUSIC_TITLE] = PMCG2_TITLE,
		[MUSIC_TITLE_MENU] = PMCG2_TITLE_MENU,
		[SOUND_MOVE] = PMCG2_MOVE,
		[SOUND_SELECT] = PMCG2_SELECT,
		[SOUND_BACK] = PMCG2_BACK,
		[SOUND_INVALID] = PMCG2_INVALID
	},
	[GAME_YELLOW] = {
		[MUSIC_STARTUP] = YELLOW_STARTUP,
		[MUSIC_TITLE] = YELLOW_TITLE,
		[MUSIC_TITLE_MENU] = YELLOW_TITLE_MENU,
		//[SOUND_MOVE] = YELLOW_MOVE,
		[SOUND_SELECT] = YELLOW_SELECT,
		[SOUND_BACK] = YELLOW_BACK,
		[SOUND_INVALID] = YELLOW_INVALID
	}
};
