#include "enums/enums.c"
#include "strings/strings.c"
#include "structs/structs.c"
#include "data/data.c"
#include "config/config.c"
#include "theme/theme.c"
#include "font/font.c"
#include "mouse/mouse.c"
#include "window/window.c"
#include "input/input.c"
#include "audio/audio.c"
#include "ui/ui.c"
#include "core/crypt.c"

#include "state/state.c"
//#include "core/save.c"
#include "player/player.c"
#include "test/test.c"
