#--------------------------------------#
#
#	raylib
#
#--------------------------------------#
if(${PMCG_SOFTWARE_RENDERER})
	set(OPENGL_VERSION "Software")
elseif("${OPENGL_VERSION}" STREQUAL "")
	set(OPENGL_VERSION "OFF")
endif()
# raylib build setup
add_library(raylib STATIC IMPORTED GLOBAL)
set(RAYLIB_LIB "${DEP_INSTALL_DIR}/lib64/libraylib.a")
set_target_properties(raylib PROPERTIES
	IMPORTED_LOCATION "${RAYLIB_LIB}"
	INTERFACE_LINK_LIBRARIES "sdl"
)
set(RAYLIB_SOURCE_DIR "${CMAKE_SOURCE_DIR}/external/raylib")
if(NOT EXISTS "${RAYLIB_SOURCE_DIR}")
    execute_process(
        COMMAND git clone --recursive https://github.com/raysan5/raylib.git "${RAYLIB_SOURCE_DIR}"
        RESULT_VARIABLE GIT_RESULT
    )
    if(NOT GIT_RESULT EQUAL 0)
        message(FATAL_ERROR "Failed to clone raylib")
    endif()
elseif(UPDATE_DEPS)
    execute_process(
        WORKING_DIRECTORY "${RAYLIB_SOURCE_DIR}"
        COMMAND git pull
        RESULT_VARIABLE GIT_RESULT
    )
    if(NOT GIT_RESULT EQUAL 0)
        message(FATAL_ERROR "Failed to update raylib")
    endif()
endif()
if(NOT EXISTS "${RAYLIB_LIB}" OR BUILD_DEPS OR PMCG_RAYLIB)
	ExternalProject_Add(libraylib
		SOURCE_DIR "${RAYLIB_SOURCE_DIR}"
		PREFIX "${DEP_BUILD_DIR}/raylib"
		BUILD_ALWAYS ${BUILD_DEPS}
		BUILD_BYPRODUCTS "${RAYLIB_LIB}"
		CMAKE_CACHE_ARGS
			-DCMAKE_BUILD_TYPE:STRING=Release
			-DCMAKE_INSTALL_PREFIX:STRING=${DEP_INSTALL_DIR}
			-DBUILD_SHARED_LIBS:BOOL=OFF
			-DBUILD_TESTING:BOOL=OFF
			-DPLATFORM:STRING=SDL
			-DOPENGL_VERSION:STRING=${OPENGL_VERSION}
			-DBUILD_EXAMPLES:BOOL=OFF
			-DSUPPORT_BUSY_WAIT_LOOP:BOOL=OFF
			-DSUPPORT_CAMERA_SYSTEM:BOOL=ON
			-DSUPPORT_CLIPBOARD_IMAGE:BOOL=OFF
			-DSUPPORT_COMPRESSION_API:BOOL=OFF
			-DSUPPORT_CUSTOM_FRAME_CONTROL:BOOL=ON
			-DSUPPORT_FILEFORMAT_ASTC:BOOL=OFF
			-DSUPPORT_FILEFORMAT_BDF:BOOL=OFF
			-DSUPPORT_FILEFORMAT_BMP:BOOL=OFF
			-DSUPPORT_FILEFORMAT_DDS:BOOL=OFF
			-DSUPPORT_FILEFORMAT_FLAC:BOOL=ON
			-DSUPPORT_FILEFORMAT_FNT:BOOL=OFF
			-DSUPPORT_FILEFORMAT_GIF:BOOL=ON
			-DSUPPORT_FILEFORMAT_GLTF:BOOL=OFF
			-DSUPPORT_FILEFORMAT_HDR:BOOL=OFF
			-DSUPPORT_FILEFORMAT_IQM:BOOL=OFF
			-DSUPPORT_FILEFORMAT_JPG:BOOL=OFF
			-DSUPPORT_FILEFORMAT_KTX:BOOL=OFF
			-DSUPPORT_FILEFORMAT_M3D:BOOL=OFF
			-DSUPPORT_FILEFORMAT_MOD:BOOL=OFF
			-DSUPPORT_FILEFORMAT_MP3:BOOL=OFF
			-DSUPPORT_FILEFORMAT_MTL:BOOL=OFF
			-DSUPPORT_FILEFORMAT_OBJ:BOOL=OFF
			-DSUPPORT_FILEFORMAT_OGG:BOOL=ON
			-DSUPPORT_FILEFORMAT_PIC:BOOL=OFF
			-DSUPPORT_FILEFORMAT_PKM:BOOL=OFF
			-DSUPPORT_FILEFORMAT_PNG:BOOL=ON
			-DSUPPORT_FILEFORMAT_PSD:BOOL=OFF
			-DSUPPORT_FILEFORMAT_PVR:BOOL=OFF
			-DSUPPORT_FILEFORMAT_QOA:BOOL=ON
			-DSUPPORT_FILEFORMAT_QOI:BOOL=ON
			-DSUPPORT_FILEFORMAT_TGA:BOOL=OFF
			-DSUPPORT_FILEFORMAT_TTF:BOOL=ON
			-DSUPPORT_FILEFORMAT_VOX:BOOL=OFF
			-DSUPPORT_FILEFORMAT_WAV:BOOL=OFF
			-DSUPPORT_FILEFORMAT_XM:BOOL=OFF
			-DSUPPORT_GESTURES_SYSTEM:BOOL=ON
			-DSUPPORT_GPU_SKINNING:BOOL=ON
			-DSUPPORT_IMAGE_EXPORT:BOOL=ON
			-DSUPPORT_IMAGE_GENERATION:BOOL=ON
			-DSUPPORT_MESH_GENERATION:BOOL=ON
			-DSUPPORT_MODULE_RAUDIO:BOOL=ON
			-DSUPPORT_MODULE_RMODELS:BOOL=ON
			-DSUPPORT_MODULE_RSHAPES:BOOL=ON
			-DSUPPORT_MODULE_RTEXT:BOOL=ON
			-DSUPPORT_MODULE_RTEXTURES:BOOL=ON
			-DSUPPORT_MOUSE_GESTURES:BOOL=ON
			-DSUPPORT_PARTIALBUSY_WAIT_LOOP:BOOL=OFF
			-DSUPPORT_QUADS_DRAW_MODE:BOOL=ON
			-DSUPPORT_RPRAND_GENERATOR:BOOL=ON
			-DSUPPORT_SCREEN_CAPTURE:BOOL=ON
			-DSUPPORT_SSH_KEYBOARD_RPI:BOOL=ON
			-DSUPPORT_TRACELOG:BOOL=ON
			-DSUPPORT_WINMM_HIGHRES_TIMER:BOOL=ON
	)
	add_dependencies(raylib libraylib)
else()
	message(STATUS "raylib found at ${RAYLIB_LIB} - skipping build")
endif()
