uint16_t gamepad_input[INPUT] = {
	[INPUT_A] = GAMEPAD_BUTTON_RIGHT_FACE_DOWN,
	[INPUT_B] = GAMEPAD_BUTTON_RIGHT_FACE_RIGHT,
	[INPUT_X] = GAMEPAD_BUTTON_RIGHT_FACE_LEFT,
	[INPUT_Y] = GAMEPAD_BUTTON_RIGHT_FACE_UP,
	[INPUT_UP] = GAMEPAD_BUTTON_LEFT_FACE_UP,
	[INPUT_DOWN] = GAMEPAD_BUTTON_LEFT_FACE_DOWN,
	[INPUT_LEFT] = GAMEPAD_BUTTON_LEFT_FACE_LEFT,
	[INPUT_RIGHT] = GAMEPAD_BUTTON_LEFT_FACE_RIGHT,
	[INPUT_START] = GAMEPAD_BUTTON_MIDDLE_RIGHT,
	[INPUT_SELECT] = GAMEPAD_BUTTON_MIDDLE_LEFT
};
