uint16_t keyboard_input[INPUT] = {
	[INPUT_A] = KEY_END,
	[INPUT_B] = KEY_PAGE_DOWN,
	[INPUT_X] = KEY_HOME,
	[INPUT_Y] = KEY_PAGE_UP,
	[INPUT_UP] = KEY_UP,
	[INPUT_DOWN] = KEY_DOWN,
	[INPUT_LEFT] = KEY_LEFT,
	[INPUT_RIGHT] = KEY_RIGHT,
	[INPUT_START] = KEY_ENTER,
	[INPUT_SELECT] = KEY_BACKSLASH,
	[INPUT_L] = INPUT_NOBIND,
	[INPUT_R] = INPUT_NOBIND,
};
