uint16_t keyboard_input[INPUT] = {
	[INPUT_A] = KEY_Z,
	[INPUT_B] = KEY_X,
	[INPUT_X] = KEY_A,
	[INPUT_Y] = KEY_S,
	[INPUT_UP] = KEY_UP,
	[INPUT_DOWN] = KEY_DOWN,
	[INPUT_LEFT] = KEY_LEFT,
	[INPUT_RIGHT] = KEY_RIGHT,
	[INPUT_START] = KEY_ENTER,
	[INPUT_SELECT] = KEY_BACKSLASH
};
