uint16_t mouse_input[INPUT] = {
	[INPUT_A] = MOUSE_BUTTON_LEFT,
	[INPUT_B] = MOUSE_BUTTON_RIGHT,
	[INPUT_X] = INPUT_NOBIND,
	[INPUT_Y] = INPUT_NOBIND,
	[INPUT_UP] = INPUT_NOBIND,
	[INPUT_DOWN] = INPUT_NOBIND,
	[INPUT_LEFT] = INPUT_NOBIND,
	[INPUT_RIGHT] = INPUT_NOBIND,
	[INPUT_START] = MOUSE_BUTTON_MIDDLE,
	[INPUT_SELECT] = INPUT_NOBIND,
	[INPUT_L] = INPUT_NOBIND,
	[INPUT_R] = INPUT_NOBIND,
};
